name: Build artifact and publish to crates.io

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - name: Install nextest
        run: cargo binstall --no-confirm cargo-nextest
      - name: Build and run tests
        run: cargo nextest run --verbose
      - name: Publish to crates.io
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --allow-dirty
